import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("GitHub Pages site reads static data and leaves sync controls in GitHub Actions", async () => {
  const html = await readFile(new URL("../github-pages/index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../github-pages/assets/app.js", import.meta.url), "utf8");
  const styles = await readFile(new URL("../github-pages/assets/styles.css", import.meta.url), "utf8");
  const viewModel = await readFile(new URL("../github-pages/assets/view-model.js", import.meta.url), "utf8");
  const workflow = await readFile(new URL("../.github/workflows/weread-sync.yml", import.meta.url), "utf8");
  const mainNav = html.match(/<nav class="mainNav"[\s\S]*?<\/nav>/)?.[0] ?? "";

  assert.match(html, /assets\/app\.js/);
  assert.match(html, /id="overviewPanel"/);
  assert.match(html, /data-tab="journey"/);
  assert.doesNotMatch(mainNav, /data-tab="journey"/);
  assert.match(html, /id="journeyTeaser"/);
  assert.match(html, /阅读完整心路/);
  assert.match(html, /class="visitorStats"/);
  assert.match(html, /counterapi\.com\/c\.js\?ns=zhenshu-reading-room/);
  assert.match(html, /id="journeyPanel"/);
  assert.match(html, /id="journeyArchiveList"/);
  assert.match(html, /id="overviewTimeline"/);
  assert.match(html, /id="overviewCalendarGrid"/);
  assert.match(html, /id="currentBook"/);
  assert.match(html, /id="shelfPagination"/);
  assert.match(html, /id="notesPagination"/);
  assert.match(html, /id="calendarGrid"/);
  assert.doesNotMatch(html, /手动同步|syncModal|syncForm|actionsLink/);
  assert.match(app, /\.\/view-model\.js/);
  assert.match(app, /data\/reading-room\.json/);
  assert.match(app, /renderTimelineNote/);
  assert.match(app, /searchedNotes/);
  assert.match(app, /SHELF_PAGE_SIZE = 8/);
  assert.match(app, /class="coverImage"/);
  assert.match(app, /class="coverFallback"/);
  assert.match(app, /class="currentBookImage"/);
  assert.match(app, /loading="lazy"/);
  assert.match(app, /reading-journey\.json/);
  assert.match(app, /renderJourney/);
  assert.match(app, /journeyTeaserTitle/);
  assert.match(app, /history\.filter\(\(entry\) => entry\.id !== payload\.id\)/);
  assert.match(app, /阅读数据暂时无法读取/);
  assert.match(app, /Array\.isArray\(state\.data\.books\)/);
  assert.match(viewModel, /Asia\/Shanghai/);
  assert.match(styles, /\.cover\.hasCover \.coverFallback/);
  assert.doesNotMatch(html + app + viewModel + workflow, /\/api\/sync/);
  assert.doesNotMatch(workflow, /SITES_BASE_URL|SYNC_AUTOMATION_TOKEN|run-weread-sync/);
  assert.match(workflow, /actions\/deploy-pages@v4/);
  assert.match(workflow, /WEREAD_API_KEY/);
  assert.match(workflow, /workflow_dispatch/);
  assert.match(workflow, /30 15 \* \* \*/);
  assert.match(workflow, /15 16 \* \* 0/);
  assert.match(workflow, /DEEPSEEK_API_KEY/);
  assert.match(workflow, /analyze-reading-journey\.mjs/);
});
